
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/homebrew/opt/openssl@3/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/Users/yangyiru/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/Users/yangyiru/.rbenv/shims/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Library/TeX/texbin/"
      - "/opt/homebrew/Caskroom/miniforge/base/bin/"
      - "/opt/homebrew/Caskroom/miniforge/base/condabin/"
      - "/Users/yangyiru/.local/bin/"
      - "/opt/homebrew/lib/ruby/gems/3.4.0/bin/"
    searched_directories:
      - "/opt/homebrew/opt/openssl@3/bin/uname"
      - "/opt/homebrew/opt/ruby/bin/uname"
      - "/Users/yangyiru/.nix-profile/bin/uname"
      - "/nix/var/nix/profiles/default/bin/uname"
      - "/Users/yangyiru/.rbenv/shims/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/openssl@3/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/yangyiru/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/Users/yangyiru/.rbenv/shims"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/Caskroom/miniforge/base/bin"
        - "/opt/homebrew/Caskroom/miniforge/base/condabin"
        - "/opt/homebrew/opt/openssl@3/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/yangyiru/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/Users/yangyiru/.rbenv/shims"
        - "/Users/yangyiru/.local/bin"
        - "/opt/homebrew/lib/ruby/gems/3.4.0/bin"
        - "/Users/yangyiru/.local/bin"
        - "/opt/homebrew/lib/ruby/gems/3.4.0/bin"
        - "/Users/yangyiru/.local/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/opt/homebrew/opt/openssl@3/bin/"
      - "/opt/homebrew/opt/ruby/bin/"
      - "/Users/yangyiru/.nix-profile/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/Users/yangyiru/.rbenv/shims/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Library/TeX/texbin/"
      - "/opt/homebrew/Caskroom/miniforge/base/bin/"
      - "/opt/homebrew/Caskroom/miniforge/base/condabin/"
      - "/Users/yangyiru/.local/bin/"
      - "/opt/homebrew/lib/ruby/gems/3.4.0/bin/"
    searched_directories:
      - "/opt/homebrew/opt/openssl@3/bin/install_name_tool"
      - "/opt/homebrew/opt/ruby/bin/install_name_tool"
      - "/Users/yangyiru/.nix-profile/bin/install_name_tool"
      - "/nix/var/nix/profiles/default/bin/install_name_tool"
      - "/Users/yangyiru/.rbenv/shims/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.12/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/openssl@3/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/yangyiru/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/Users/yangyiru/.rbenv/shims"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Library/Frameworks/Python.framework/Versions/3.12/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/Caskroom/miniforge/base/bin"
        - "/opt/homebrew/Caskroom/miniforge/base/condabin"
        - "/opt/homebrew/opt/openssl@3/bin"
        - "/opt/homebrew/opt/ruby/bin"
        - "/Users/yangyiru/.nix-profile/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/Users/yangyiru/.rbenv/shims"
        - "/Users/yangyiru/.local/bin"
        - "/opt/homebrew/lib/ruby/gems/3.4.0/bin"
        - "/Users/yangyiru/.local/bin"
        - "/opt/homebrew/lib/ruby/gems/3.4.0/bin"
        - "/Users/yangyiru/.local/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
